"""Regenerate the run table in chaos/README.md from last_run.json.

Docs that restate numbers by hand drift the moment a scenario is added, and a project
about honest reporting cannot ship stale counts. Run after any harness run.
"""
import json, pathlib

run = json.load(open(pathlib.Path(__file__).parent / "last_run.json"))
rows = "\n".join(
    f"{r['name']:<27} {r['verdict']:<9} {r.get('severity','-'):<7} {r.get('claim','')[:44]}"
    for r in run)
f = [r for r in run if r["verdict"] == "FINDING"]
hi = [r for r in f if r.get("severity") == "HIGH"]

block = f"""<!--RUN-->
```
{'scenario':<27} {'verdict':<9} {'sev':<7} claim
{rows}
```

**{len(f)} findings / {len(run)} scenarios**, {len(hi)} HIGH, {len(run)-len(f)} passed.
This block is generated by `chaos/sync_readme.py` from `last_run.json`, so it cannot
drift from the last real run.
<!--/RUN-->"""

p = pathlib.Path(__file__).parent / "README.md"
t = p.read_text()
a, b = t.index("<!--RUN-->"), t.index("<!--/RUN-->") + len("<!--/RUN-->")
p.write_text(t[:a] + block + t[b:])
print("synced chaos/README.md")
