"""Regenerate the run tables in chaos/README.md and the root README.md.

Docs that restate numbers by hand drift the moment a scenario is added, and a project
about honest reporting cannot ship stale counts. Run after any harness run.

The root README was originally maintained by hand and drifted exactly as predicted:
it announced "2 HIGH, 4 MEDIUM" above a table listing 4 HIGH and 2 MEDIUM, kept a
heading called "The four HIGH findings" after two were downgraded, and omitted a
scenario entirely. Caught by @emmanuelist reading it. Both tables are generated now,
from the same run, so the two cannot disagree with each other or with reality.
"""
import json, pathlib

run = json.load(open(pathlib.Path(__file__).parent / "last_run.json"))
rows = "\n".join(
    f"{r['name']:<27} {r['verdict']:<9} {r.get('severity','-'):<7} {r.get('claim','')[:44]}"
    for r in run)
f = [r for r in run if r["verdict"] == "FINDING"]
hi = [r for r in f if r.get("severity") == "HIGH"]

block = f"""<!--RUN-->
```
{'scenario':<27} {'verdict':<9} {'sev':<7} claim
{rows}
```

**{len(f)} findings / {len(run)} scenarios**, {len(hi)} HIGH, {len(run)-len(f)} passed.
This block is generated by `chaos/sync_readme.py` from `last_run.json`, so it cannot
drift from the last real run.
<!--/RUN-->"""

# The root README wants a tighter table: no claim column, findings first, so the
# severities a reader scans first are the ones that matter.
order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2, "-": 3}
ranked = sorted(run, key=lambda r: (r["verdict"] != "FINDING",
                                    order.get(r.get("severity", "-"), 9), r["name"]))
short = {
    "prose_drift": "payload-hash idempotency key drifts",
    "premise_staleness": "premise false by the time tx lands",
    "conditional_staleness": "KeeperHub's own guard is not atomic",
    "silent_noop_node": "skipped action node reports success",
    "omitted_key": "duplicate protection is opt-in",
    "amount_formatting": "our own fix needs value normalization",
    "semantic_key_fix": "semantic key survives reworded prose",
    "body_drift_conflict": "drifted body fails closed, not open",
    "concurrent_same_key": "dedupe is atomic under races",
    "cross_chain_key_scope": "key<->payload binding enforced",
    "revert_reporting": "reverts reported honestly",
    "overdraft_transfer": "no stuck nonce on unaffordable send",
    "parallel_distinct_transfers": "nonce ordering holds under load",
}
sev = {s: sum(1 for r in f if r.get("severity") == s) for s in ("HIGH", "MEDIUM", "LOW")}
tally = " · ".join(f"{n} {s}" for s, n in sev.items() if n)
root_rows = "\n".join(
    f"{r['name']:<27} {r['verdict']:<9} {r.get('severity','-'):<7} "
    f"{short.get(r['name'], r.get('claim','')[:40])}"
    for r in ranked)
root_block = f"""<!--RUN-->
**{len(run)} scenarios · {len(f)} findings · {tally} · {len(run)-len(f)} passes.** Every run executes real
transactions on Ethereum Sepolia. Gas is sponsored and transfers are self-directed, so a
full pass costs nothing and is repeatable indefinitely.

```
{root_rows}
```
<!--/RUN-->"""


def splice(path, text):
    p = pathlib.Path(path)
    t = p.read_text()
    a, b = t.index("<!--RUN-->"), t.index("<!--/RUN-->") + len("<!--/RUN-->")
    p.write_text(t[:a] + text + t[b:])
    print(f"synced {path}")


here = pathlib.Path(__file__).parent
splice(here / "README.md", block)
splice(here.parent / "README.md", root_block)
